import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { verifiedArtifacts, metadataName } from './artifacts.mjs';
import { releaseSettings } from './config.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const target = process.argv[2] || `${process.platform}-${process.arch}`;
const { repo, channel } = releaseSettings(process.env, target);
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'apps/desktop/package.json')));
const tag = `v${pkg.version}`;
const localHead = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' });
const releaseCommit = process.env.AMIBA_RELEASE_COMMIT || localHead.stdout?.trim();
if (!/^[a-f0-9]{40}$/.test(releaseCommit || '')) throw new Error('Cannot resolve release source commit');
const dir = path.join(root, 'apps/desktop/dist', target);
const metadata = metadataName(target);
const names = verifiedArtifacts(dir, target, pkg.version).filter(name => name !== metadata);
const run = (args, capture = false) => {
  const result = spawnSync('gh', args, { cwd: root, stdio: capture ? 'pipe' : 'inherit', encoding: 'utf8' });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(`gh command failed: ${result.stderr || result.status}`);
  return result.stdout;
};
// Reuse drafts only. Published versions are immutable; never overwrite live installers.
const releases = JSON.parse(run(['release', 'list', '--repo', repo, '--limit', '100', '--json', 'tagName,isDraft'], true));
const existing = releases.find(r => r.tagName === tag);
if (existing && !existing.isDraft) throw new Error(`${tag} is already published. Increment the version.`);
if (!existing) run(['release', 'create', tag, '--repo', repo, '--draft', '--target', releaseCommit, '--title', tag, '--notes', `Amiba ${pkg.version}`]);
run(['release', 'upload', tag, '--repo', repo, ...names.map(name => path.join(dir, name)), path.join(dir, metadata), '--clobber']);
console.log(`Uploaded ${target} to draft ${repo} ${tag}. Publish only after all three targets and CDN sync are verified.`);
