/** Shared presentation vocabulary; schema keys and saved values remain provider-owned. */
export const providerFieldKeys: Record<string, string> = {
  apiKeyEnv: "apiKeyEnv",
  apiKey: "apiKey",
  baseURL: "baseURL",
  maxTokens: "maxTokens",
  defaultContextWindow: "defaultContextWindow",
  contextWindow: "contextWindow",
  reasoningEffort: "reasoningEffort",
  thinking: "thinking",
  models: "models",
  id: "id",
  name: "name",
  displayName: "displayName",
  model: "model",
  temperature: "temperature",
  topP: "topP",
  timeout: "timeout",
  maxRetries: "maxRetries",
  region: "region",
  projectId: "projectId",
  organization: "organization",
  headers: "headers",
  enabled: "enabled",
  supportsVision: "supportsVision",
  supportsTools: "supportsTools",
  supportsReasoning: "supportsReasoning",
  inputPrice: "inputPrice",
  outputPrice: "outputPrice",
  baseUrl: "baseURL",
  endpoint: "baseURL",
  maxOutputTokens: "maxTokens",
  max_tokens: "maxTokens",
  max_output_tokens: "maxTokens",
  context_window: "contextWindow",
  reasoning_effort: "reasoningEffort",
  top_p: "topP",
  api: "api",
  modelOverrides: "modelOverrides",
  compat: "compat",
  input: "input",
  defaultInput: "defaultInput",
  reasoningEfforts: "reasoningEfforts",
  thinkingBudgets: "thinkingBudgets",
  cacheRetention: "cacheRetention",
  transport: "transport",
  timeoutMs: "timeoutMs",
  websocketConnectTimeoutMs: "websocketConnectTimeoutMs",
  streamIdleTimeoutMs: "streamIdleTimeoutMs",
  maxRequestImageBytes: "maxRequestImageBytes",
  requestImagePixelBudget: "requestImagePixelBudget",
  requestImageMaxBytes: "requestImageMaxBytes",
  retryPolicy: "retryPolicy",
  supportsStore: "supportsStore",
  supportsDeveloperRole: "supportsDeveloperRole",
  supportsReasoningEffort: "supportsReasoningEffort",
  supportsUsageInStreaming: "supportsUsageInStreaming",
  maxTokensField: "maxTokensField",
  requiresToolResultName: "requiresToolResultName",
  requiresAssistantAfterToolResult: "requiresAssistantAfterToolResult",
  requiresThinkingAsText: "requiresThinkingAsText",
  requiresReasoningContentOnAssistantMessages:
    "requiresReasoningContentOnAssistantMessages",
  thinkingFormat: "thinkingFormat",
  chatTemplateKwargs: "chatTemplateKwargs",
  supportsStrictMode: "supportsStrictMode",
  cacheControlFormat: "cacheControlFormat",
  supportsLongCacheRetention: "supportsLongCacheRetention",
  supportsEagerToolInputStreaming: "supportsEagerToolInputStreaming",
  supportsCacheControlOnTools: "supportsCacheControlOnTools",
  supportsTemperature: "supportsTemperature",
  forceAdaptiveThinking: "forceAdaptiveThinking",
  allowEmptySignature: "allowEmptySignature",
  supportsStrictTools: "supportsStrictTools",
  defaultMaxTokens: "maxTokens",
  reasoning: "reasoningEffort",
};
export const providerFieldMessages = {
  en: {
    "provider.refresh": "Refresh",
    "provider.field.api": "API protocol",
    "provider.field.modelOverrides": "Model overrides",
    "provider.field.compat": "Protocol compatibility",
    "provider.field.input": "Supported input types",
    "provider.field.defaultInput": "Default input types",
    "provider.field.reasoningEfforts": "Supported reasoning levels",
    "provider.field.thinkingBudgets": "Reasoning budget by level",
    "provider.field.cacheRetention": "Cache retention",
    "provider.field.transport": "Connection method",
    "provider.field.timeoutMs": "Request timeout (ms)",
    "provider.field.websocketConnectTimeoutMs":
      "WebSocket connection timeout (ms)",
    "provider.field.streamIdleTimeoutMs": "Response inactivity timeout (ms)",
    "provider.field.maxRequestImageBytes": "Total request image limit (bytes)",
    "provider.field.requestImagePixelBudget": "Image pixel budget",
    "provider.field.requestImageMaxBytes": "Per-image size limit (bytes)",
    "provider.field.retryPolicy": "Retry policy",
    "provider.field.supportsStore": "Response storage",
    "provider.field.supportsDeveloperRole": "Developer messages",
    "provider.field.supportsReasoningEffort": "Reasoning depth control",
    "provider.field.supportsUsageInStreaming": "Streaming usage reports",
    "provider.field.maxTokensField": "Reply length parameter format",
    "provider.field.requiresToolResultName": "Include tool names in results",
    "provider.field.requiresAssistantAfterToolResult":
      "Assistant message after tool results",
    "provider.field.requiresThinkingAsText": "Send reasoning as text",
    "provider.field.requiresReasoningContentOnAssistantMessages":
      "Include reasoning in assistant messages",
    "provider.field.thinkingFormat": "Reasoning format",
    "provider.field.chatTemplateKwargs": "Chat template parameters",
    "provider.field.supportsStrictMode": "Strict output format",
    "provider.field.cacheControlFormat": "Cache control format",
    "provider.field.supportsLongCacheRetention": "Extended cache retention",
    "provider.field.supportsEagerToolInputStreaming":
      "Early streaming of tool input",
    "provider.field.supportsCacheControlOnTools": "Tool cache control",
    "provider.field.supportsTemperature": "Response variety control",
    "provider.field.forceAdaptiveThinking": "Adaptive reasoning",
    "provider.field.allowEmptySignature": "Allow empty signatures",
    "provider.field.supportsStrictTools": "Strict tool parameters",

    "provider.field.apiKeyEnv": "API key",
    "provider.field.apiKey": "API key",
    "provider.field.baseURL": "API address",
    "provider.help.baseURL":
      "Use the service provider’s default address unless you use a proxy or custom endpoint.",
    "provider.field.maxTokens": "Maximum reply length",
    "provider.help.maxTokens":
      "Limits a single reply, measured in tokens, not characters. Usually leave the default.",
    "provider.field.defaultContextWindow": "Conversation context capacity",
    "provider.help.defaultContextWindow":
      "How much conversation the model can use at once, measured in tokens. Keep the model’s supported limit.",
    "provider.field.contextWindow": "Context capacity",
    "provider.help.contextWindow":
      "How much content this model can use at once, measured in tokens.",
    "provider.field.reasoningEffort": "Reasoning depth",
    "provider.help.reasoningEffort":
      "Deeper reasoning may take longer. Use the default for everyday tasks.",
    "provider.field.thinking": "Deep thinking",
    "provider.help.thinking":
      "Let the model spend more time reasoning before it answers.",
    "provider.field.models": "Custom models",
    "provider.help.models":
      "Only add models here when the automatically loaded list does not meet your needs.",
    "provider.field.id": "Model ID",
    "provider.field.name": "Display name",
    "provider.field.displayName": "Display name",
    "provider.field.model": "Model",
    "provider.field.temperature": "Response variety",
    "provider.help.temperature":
      "Higher values make answers more varied. Usually leave the default.",
    "provider.field.topP": "Sampling range",
    "provider.help.topP":
      "An advanced response variety control. Usually leave the default.",
    "provider.field.timeout": "Request timeout",
    "provider.field.maxRetries": "Retry limit",
    "provider.field.region": "Region",
    "provider.field.projectId": "Project ID",
    "provider.field.organization": "Organization",
    "provider.field.headers": "Custom request headers",
    "provider.field.enabled": "Enabled",
    "provider.field.supportsVision": "Image understanding",
    "provider.field.supportsTools": "Tool calling",
    "provider.field.supportsReasoning": "Reasoning support",
    "provider.field.inputPrice": "Input price",
    "provider.field.outputPrice": "Output price",
    "provider.options": "Advanced settings",
    "provider.keySaved": "Saved",
    "provider.removeKey": "Remove key",
    "provider.removeProvider": "Remove provider",
    "provider.modelEntry": "Model",
    "provider.choice.enabled": "On",
    "provider.choice.disabled": "Off",
    "provider.choice.auto": "Automatic",
    "provider.choice.adaptive": "Adaptive",
  },
  "zh-CN": {
    "provider.refresh": "刷新",
    "provider.field.api": "接口协议",
    "provider.field.modelOverrides": "模型单独设置",
    "provider.field.compat": "协议兼容设置",
    "provider.field.input": "支持的输入类型",
    "provider.field.defaultInput": "默认输入类型",
    "provider.field.reasoningEfforts": "可选思考深度",
    "provider.field.thinkingBudgets": "各档思考用量",
    "provider.field.cacheRetention": "缓存保留时长",
    "provider.field.transport": "连接方式",
    "provider.field.timeoutMs": "请求超时（毫秒）",
    "provider.field.websocketConnectTimeoutMs": "长连接建立超时（毫秒）",
    "provider.field.streamIdleTimeoutMs": "回复停滞超时（毫秒）",
    "provider.field.maxRequestImageBytes": "单次请求图片总大小上限（字节）",
    "provider.field.requestImagePixelBudget": "图片像素上限",
    "provider.field.requestImageMaxBytes": "单张图片大小上限（字节）",
    "provider.field.retryPolicy": "失败重试设置",
    "provider.field.supportsStore": "存储回复",
    "provider.field.supportsDeveloperRole": "开发者消息",
    "provider.field.supportsReasoningEffort": "思考深度调节",
    "provider.field.supportsUsageInStreaming": "流式用量统计",
    "provider.field.maxTokensField": "回复长度参数格式",
    "provider.field.requiresToolResultName": "工具结果包含工具名称",
    "provider.field.requiresAssistantAfterToolResult": "工具结果后附加助手消息",
    "provider.field.requiresThinkingAsText": "以文本发送思考内容",
    "provider.field.requiresReasoningContentOnAssistantMessages":
      "助手消息包含思考内容",
    "provider.field.thinkingFormat": "思考内容格式",
    "provider.field.chatTemplateKwargs": "对话模板参数",
    "provider.field.supportsStrictMode": "严格输出格式",
    "provider.field.cacheControlFormat": "缓存控制格式",
    "provider.field.supportsLongCacheRetention": "延长缓存保留",
    "provider.field.supportsEagerToolInputStreaming": "提前流式发送工具输入",
    "provider.field.supportsCacheControlOnTools": "工具缓存控制",
    "provider.field.supportsTemperature": "回答多样性调节",
    "provider.field.forceAdaptiveThinking": "自适应思考",
    "provider.field.allowEmptySignature": "允许空签名",
    "provider.field.supportsStrictTools": "严格工具参数",

    "provider.field.apiKeyEnv": "API 密钥",
    "provider.field.apiKey": "API 密钥",
    "provider.field.baseURL": "接口地址",
    "provider.help.baseURL":
      "通常使用服务商默认地址；使用代理或自建服务时再修改。",
    "provider.field.maxTokens": "回复长度上限",
    "provider.help.maxTokens":
      "限制单次回复的长度，单位为词元（Token），不等同于字数。通常保持默认即可。",
    "provider.field.defaultContextWindow": "对话上下文容量",
    "provider.help.defaultContextWindow":
      "模型一次可参考的对话内容量，以词元（Token）计。请按模型支持的范围设置。",
    "provider.field.contextWindow": "上下文容量",
    "provider.help.contextWindow":
      "模型一次可参考的内容量，以词元（Token）计。",
    "provider.field.reasoningEffort": "思考深度",
    "provider.help.reasoningEffort":
      "更深入的思考可能需要更长时间，日常使用保持默认即可。",
    "provider.field.thinking": "深度思考",
    "provider.help.thinking": "让模型在回答前进行更深入的思考。",
    "provider.field.models": "自定义模型",
    "provider.help.models": "自动获取的模型列表不满足需求时，再手动添加。",
    "provider.field.id": "模型标识",
    "provider.field.name": "显示名称",
    "provider.field.displayName": "显示名称",
    "provider.field.model": "模型",
    "provider.field.temperature": "回答多样性",
    "provider.help.temperature": "数值越高，回答越多样。通常保持默认即可。",
    "provider.field.topP": "采样范围",
    "provider.help.topP": "用于调整回答多样性的高级参数，通常保持默认即可。",
    "provider.field.timeout": "请求超时",
    "provider.field.maxRetries": "重试次数上限",
    "provider.field.region": "服务区域",
    "provider.field.projectId": "项目标识",
    "provider.field.organization": "组织",
    "provider.field.headers": "自定义请求头",
    "provider.field.enabled": "启用",
    "provider.field.supportsVision": "图像理解",
    "provider.field.supportsTools": "工具调用",
    "provider.field.supportsReasoning": "支持深度思考",
    "provider.field.inputPrice": "输入价格",
    "provider.field.outputPrice": "输出价格",
    "provider.options": "高级设置",
    "provider.keySaved": "已保存",
    "provider.removeKey": "移除密钥",
    "provider.removeProvider": "移除服务商",
    "provider.modelEntry": "模型",
    "provider.choice.enabled": "开启",
    "provider.choice.disabled": "关闭",
    "provider.choice.auto": "自动",
    "provider.choice.adaptive": "自适应",
  },
};
export const providerHelpKeys = new Set([
  "baseURL",
  "maxTokens",
  "defaultContextWindow",
  "contextWindow",
  "reasoningEffort",
  "thinking",
  "models",
  "temperature",
  "topP",
]);
